### PR TITLE
Optional input of DistributionMetadata DPU - DCAT Distribution model

### LINKED ISSUE #3: L-filesToCKAN DPU extension for metadata support
Adjust L-filesToCKAN DPU:
- apart from its standard files data unit input (further filesDU), it also supports metadata input (rdf data unit, called "metaDU"). Such metadata will consume output from E-distributionMetadata DPU.
- data contained in "metaDPU" should be merged with metadata attached to the entry within filesDU. In case of conflict, "metaDPU" has preference (as this metadata was inputted manually). Knap, Tomáš may help by properly matching metadata outputted from e-distributionMetadata and metadata fields on Resource object.
- Merged metadata should be loaded to CKAN. The L-filesToCkan DPU is already loading certain metadata to CKAN, so it should be just extended to load enriched and merge metadata

(cloned from OpenDataNode/ODN-UV-Plugins#2)

### PR DESCRIPTION
**Pull request by ghost**
resolves #3

### CODE REVIEW

**Comment by tomas-knap** [comment]
Code is OK (but did not test it in ODN context, if it still loads to CKAN properly)

**Comment by tomas-knap** [comment]
@mkl-eea-sk Is you testing machine somewhere available, so that I can test it there?

**Comment by ghost** [comment]
Testing machines are rare, I do not have one at this time (but working 
on instalation of one).

**Comment by skrchnavy** [comment]
@mkl-eea-sk please merge develop into this feature branch

**Comment by ghost** [comment]
Done

**Comment by skrchnavy** [comment]
Readme.md doesn't reflect in version 1.1.0 changes, there is no info about new 'distributionInput'.

**Comment by ghost** [comment]
closing and not merging

**Comment by skrchnavy** [comment]
branch deleted, can be restored

**Pull request closed without merging**
